version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/init:/docker-entrypoint-initdb.d

  python:
    image: python:3.7.2-alpine
    container_name: python_host
    working_dir: '/usr/local/src/python'
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./docker/python:/usr/local/src/python
    links:
      - db

  # golang:
  #   image: golang:1.11-alpine
  #   container_name: golang_host
  #   working_dir: '/usr/local/src/golang'
  #   tty: true
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./docker/golang:/usr/local/src/golang
  #   links:
  #     - db
